name: Security-Scans

on: 
  workflow_call:
    secrets:
      GITGUARDIAN:
        required: true
        
env:
  GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN }}
        
jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout workflows-security-scans
        uses: actions/checkout@v2
        with:
          repository: u21/workflows-security-scans
          path: workflows-security-scans

      # Install and run Bandit
      - name: Install Bandit
        run: pip install bandit
      
      - name: Run Bandit
        run: bandit -c workflows-security-scans/bandit.yaml -r .

      - name: Generate Bandit report if necessary
        if: ${{ failure() }}
        run: bandit -c workflows-security-scans/bandit.yaml -r . -f json -o bandit_report.json

      # Upload bandit result
      - name: Upload scan result if vulnerable
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Bandit-Report-JSON
          path: bandit_report.json
        
  gitguardian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install and run ggshield
      - name: Install ggshield
        run: pip install ggshield
        
      - name: Run ggshield
        run: ggshield scan path . --recursive -y
      


  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout workflows-security-scans
        uses: actions/checkout@v2
        with:
          repository: u21/workflows-security-scans
          path: workflows-security-scans
          
      # Run tfsec
      - name: Run tfsec
        run: workflows-security-scans/tfsec . --force-all-dirs
