name: Security-Scans

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  owasp-dependency-scan:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Run OWASP dependency check
      - name: Run OWASP dependency check
        if: always()
        run: dependency-check/bin/dependency-check.sh --scan . --project OWASP-Dep --failOnCVSS 0 --enableExperimental -o report.html --suppression dependency-check/suppression.xml
      
      # Upload OWASP dependency check result
      - name: Upload scan result if vulnerable
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: OWASP-Dependency-Check-Report
          path: report.html
          
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install and run Bandit
      - name: Install Bandit
        run: pip install bandit
      
      - name: Run Bandit
        run: bandit -r .
