name: Security-Scans

on: 
  workflow_call:
    secrets:
      GITGUARDIAN:
        required: true
        
env:
  GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN }}
        
jobs:
  owasp-dependency-scan:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout workflows-security-scans
        uses: actions/checkout@v2
        with:
          repository: u21/workflows-security-scans
          path: workflows-security-scans
          
      # Run OWASP dependency check
      - name: Run OWASP dependency check
        run: workflows-security-scans/dependency-check/bin/dependency-check.sh --scan . --project OWASP-Dep --failOnCVSS 0 --enableExperimental -o report.html --suppression workflows-security-scans/dependency-check/suppression.xml
      
      # Upload OWASP dependency check result
      - name: Upload scan result if vulnerable
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: OWASP-Dependency-Check-Report
          path: report.html
          
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout workflows-security-scans
        uses: actions/checkout@v2
        with:
          repository: u21/workflows-security-scans
          path: workflows-security-scans

      # Install and run Bandit
      - name: Install Bandit
        run: pip install bandit
      
      - name: Run Bandit
        run: bandit -r . workflows-security-scans/bandit.yaml
        
  gitguardian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install and run ggshield
      - name: Install ggshield
        run: pip install ggshield
        
      - name: Run ggshield
        run: ggshield scan path . --recursive -y
      


  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout workflows-security-scans
        uses: actions/checkout@v2
        with:
          repository: u21/workflows-security-scans
          path: workflows-security-scans
          
      # Run tfsec
      - name: Run tfsec
        run: workflows-security-scans/tfsec . --force-all-dirs
